- pandapipes/component_models/junction_component.py
In some combinations of numpy/pandas, it is not possible to apply np.max on a pandas Int64 Index, see:
https://github.com/numpy/numpy/issues/13285
I am experiencing this with numpy 1.17.4 and pandas 0.24.2. Using pandas .max() function instead should be more stable.
> use pandas instead of numpy max function

- .travis.yml
Right now the wrong pandapower branch is used in case of the master branch. Bugfix!
> using the right branch in case of installing pandapower

- pandapipes/test/openmodelica_comparison/pipeflow_openmodelica_comparison.py
- pandapipes/test/pipeflow_internals/test_inservice.py
* some tests failed in pandas 0.22 but not in pandas 0.25. Now, they are passing in pd 0.22 too
> print statements removed, tests adapted

- pandapipes/create.py
For some reason, some create functions had no line breaks in the list of parameters in the compiled documentation.
These changes should fix this.
> adaptions in create-docstring

- doc/source/fluid_properties/create_fluids.rst
- doc/source/fluid_properties/fluids.rst
- pandapipes/create.py
- pandapipes/properties/fluids.py
- pandapipes/test/api/test_components/test_pipe_results.py
- pandapipes/test/pipeflow_internals/test_pipeflow_analytic_comparison.py
- pandapipes/test/properties/test_fluid_specials.py
- tutorials/creating_a_simple_network.ipynb
- tutorials/minimal_example.ipynb
- tutorials/simple_plot.ipynb
- tutorials/simple_time_series_example.ipynb
* Hydrogen is now an additional default fluid and has been added to the text in the tutorials and documentation.
* if someone passed a string to add_fluid_to_net(net, fluid_as_string), it would write the string to the net. A call_lib intermediate step has been added.
* import of run_timeseries in the time series tutorial fixed
> add H2 as one default fluid in doc and tutorials, fall back option in add_fluid

- pandapipes/io/io_utils.py
if not deepcopied if pandapower and pandapipes are both imported from_serializable(class_name='pandapowerNet') is overwritten and causes problems when trying to read a json-file in pandapower
> small bug with big results

- pandapipes/control/run_control.py
* required for multinets, because pandapower errors are also tuples
> make ctrl_variables["errors"] a tuple

- pandapipes/test/pytest.ini
otherwise, a warning would be raised
> register the 'slow' marker in pytests

- .github/workflows/run_tests_develop.yml
- .github/workflows/run_tests_master.yml
- CHANGELOG.rst
* all tests pass with Python 3.10 so we should include it in the CI
> Add Python 3.10 to GHA testing matrix

- pandapipes/multinet/timeseries/run_time_series_multinet.py
* according to changes in [pandapower PR #1457](https://github.com/e2nIEE/pandapower/pull/1457)
* this change is neccessary because test_time_series_p2g_control will fail when pandapower PR 1457 is merged
* the new import tqdm will be covered by pandapower PR #1457 which adds tqdm to the pandapower dependencies
* this PR should not be merged before pandapower PR #1457 is merged
> add new tqdm progress bar to multinet time series

- pandapipes/pf/internals_toolbox.py
no significant speedup possible really
> removed type hints in numba jit signatures to avoid problems

- pandapipes/pipeflow.py
In der Dok von der Funktion pipeflow hat ein s bei mode "hydraulics" gefehlt. Habe es hinzugefügt.
> added s to hydraulic in pipeflow example

- CHANGELOG.rst
- pandapipes/create.py
0.2 mm is a more realistic than 1 mm. It is still a quite high value
closes #323 
change level: minor - should not be merged if the next release is just a bugfix release
> change k_mm in the create_pipes functions to 0.2 mm instead of 1 mm

- CHANGELOG.rst
- doc/source/about.rst
- doc/source/components.rst
- doc/source/components/flow_control/flow_control_component.rst
- doc/source/components/press_control/press_control_component.rst
- doc/source/components/press_control/press_control_par.csv
- doc/source/components/press_control/press_control_res.csv
- pandapipes/create.py
* and some minor formatting fixes for the documentation (examples were too long)
fixes #414 
contributes to #426
> add missing docu for pressure controller

- pandapipes/test/topology/__init__.py
maybe not really necessary but all other folders in the test dir have an init too
> add missing init to the topology tests

- pandapipes/test/io/test_file_io.py
- pandapipes/toolbox.py
relying change before https://github.com/e2nIEE/pandapower/pull/1886
> pp.toolbox import fix & silence numpy warnings

- .github/workflows/release.yml
- .github/workflows/run_tests_develop.yml
- .github/workflows/run_tests_master.yml
- CHANGELOG.rst
Python 3.7 tests are currently failing and there is not really a need to fix them. This PR adapts the GitHub Actions script so that Python 3.7 will no longer be tested.
closes #499
> remove Python 3.7 from test workflow

- .github/workflows/release.yml
- .github/workflows/run_tests_develop.yml
- .github/workflows/run_tests_master.yml
- pandapipes/plotting/generic_geodata.py
- pandapipes/test/plotting/test_generic_coordinates.py
- setup.py
closes #547
@jkisse I would like to add this change to the hotfix, just to have it fixed.
> replaced references to python-igraph as recommended in #547

- pandapipes/component_models/pipe_component.py
I think it makes more sense to initialize T_OUT from the values of the respective junction at the end of each pipe.
> small adaption of T_OUT in pipe component to be derived from nodes

- CHANGELOG.rst
- pandapipes/component_models/abstract_models/base_component.py
- pandapipes/component_models/component_toolbox.py
- pandapipes/component_models/compressor_component.py
- pandapipes/component_models/flow_control_component.py
- pandapipes/component_models/pump_component.py
- pandapipes/idx_branch.py
- pandapipes/pf/pipeflow_setup.py
- added "components" dict of arrays to pit
- every component can create its own internal array if needed (create_component_array in base_component.py)
- moved PRESSURE_RATIO and STD_TYPE from branch_idx.py to internal arrays of pumps and compressors, as they are only needed right there
> internal component arrays

- .readthedocs.yml
- CHANGELOG.rst
see also [read our blog post](https://blog.readthedocs.com/use-build-os-config/)
> readthedocs.yml deprecation

- pandapipes/converter/stanet/table_creation.py
- pandapipes/topology/create_graph.py
small fixes for graph creation wrt pressure circ_pumps and for stanet converter (wrong keyword)
> small fixes for graph creation

- src/pandapipes/plotting/pipeflow_results.py
- src/pandapipes/test/topology/test_graph_searches.py
- src/pandapipes/topology/__init__.py
- src/pandapipes/topology/graph_searches.py
- src/pandapipes/topology/topology_toolbox.py
Added unsupplied_junctions and elements_on_path with tests to pandapipes.
Added the convenience functions get_all_branch_component_table_names and get_all_branch_component_models to prevent hardcoding the branch element table names like in pandapower.
> Added unsupplied_junctions and elements_on_path to pandapipes

- src/pandapipes/component_models/abstract_models/branch_w_internals_models.py
- src/pandapipes/component_models/pipe_component.py
I shifted some node entries from pipe component to branch_w_internals_models.py
> Made some node entries more global than just in pipe

- src/pandapipes/component_models/__init__.py
- src/pandapipes/component_models/component_toolbox.py
- src/pandapipes/create.py
- src/pandapipes/test/api/test_components/test_pipe.py
in create_pipes_from_parameters, the check for the value of u_w_per_m2k in case of existing alpha is corrected (exception for given arrays of u)
> Hotfix for warning in case of given u_w_per_m2k in array form

- .github/workflows/release.yml
- .github/workflows/run_tests_develop.yml
- .github/workflows/run_tests_master.yml
- CHANGELOG.rst
- pyproject.toml
- src/pandapipes/test/test_imports.py
chore: removed python 3.8 from pyproject.toml and from all python versions in workflow matrix
TODO: We should check for the python versions with which to run
- codacy
- codecov
- some numba stuff (currently done with python 3.11)
> Chore: EOL of python v 3.8

- src/pandapipes/component_models/heat_consumer_component.py
the return temperature of the heat consumer is not fixed for the solver anymore, but calculated based on an exact estimate of qext from inlet and controlled return temperature
> Small correction in heat consumer for mode MF_TR

- .github/workflows/relying_test_on_dev_merge.yml
- .github/workflows/run_tests_develop.yml
- .github/workflows/run_tests_master.yml
- .readthedocs.yml
- doc/requirements.txt
- pyproject.toml
This PR cleans up the GA workflow files.
* tests on commits pushed to dev / feature branches now finish in ~4min (was: 13min)
* total CI time for these tests is at ~25min (was: ~2h)
> speeding up tests in GA

- doc/source/controller/run.rst
I found a small mistake in the doc, the function is named run_control, like in pandapower
> Correct controller documentation

- src/pandapipes/create.py
let set_multiple_entries and preserve_dtypes handle bool dtype coercion for heat consumers and exchangers (error in implementation)
> avoid bool(in_service) for bulk create functions

- src/pandapipes/timeseries/run_time_series.py
This update modifies the init_default_outputwriter function to check whether components exist in the network before logging their variables. Previously, the function unconditionally logged variables for certain components (like sinks, sources, pipes, etc.), which caused errors when those components were missing from the network. By adding checks with hasattr(net, component), the output writer now only logs variables for components that are actually present, improving robustness and preventing runtime errors during time series calculations.
> Modified output writer to log only existing components to avoid errors
