pandapipes/plotting/collections.py
this version should only consider passed sinks while refering to the index, not the position of the geodata
=> updated sink collection

setup.py
for full functionality, 2.2.2 is required
=> Changed requirement to pandapower 2.2

pandapipes/test/pipeflow_internals/test_inservice.py
test to check if pipeflow converges with an unconnected junction in net.junctions
=> testing pipeflow with unconnected junction

pandapipes/__init__.py, pandapipes/test/test_toolbox.py, pandapipes/toolbox.py
Adapted from pandapower. Are all relevant elements considered in element_junction_tuples?
=> reindex_junction function implemented

CONTRIBUTING.rst, pandapipes/pipeflow_setup.py, pandapipes/plotting/collections.py
now with successful travis-ci on fork
=> no more usage of assert in normal code (2nd try)

pandapipes/component_models/pipe_component.py, pandapipes/test/pipeflow_internals/test_time_series.py
equal signs cause problems due to system accuracy. Changed to almost equal comparisons
=> System Accuracy

pandapipes/component_models/junction_component.py, pandapipes/pipeflow.py
If there are no junctions and pipes it should still be possible to make a pipeflow. However, no result tables should be displayed
=> empty network pipeflow

pandapipes/plotting/collections.py, pandapipes/plotting/simple_plot.py
- changing patch color of source and sink as well as their linewidths (simple_plot.py)
- fixing a bug in source collection (collections.py)
=> sink_source issues

pandapipes/component_models/abstract_models/branch_models.py, pandapipes/component_models/abstract_models/branch_wzerolength_models.py, pandapipes/component_models/abstract_models/const_flow_models.py, pandapipes/component_models/auxiliaries/build_system_matrix.py, pandapipes/component_models/auxiliaries/derivative_toolbox.py, pandapipes/component_models/circulation_pump_mass_component.py, pandapipes/component_models/circulation_pump_pressure_component.py, pandapipes/component_models/ext_grid_component.py, pandapipes/component_models/heat_exchanger_component.py, pandapipes/component_models/pipe_component.py, pandapipes/component_models/valve_component.py, pandapipes/internals_toolbox.py, pandapipes/plotting/collections.py, pandapipes/test/test_toolbox.py, pandapipes/toolbox.py
I also moved _sum_by_group to a new module internals_toolbox.py
=> new toolbox functions

pandapipes/test/run_tests.py
changes in pandapower required changes in pandapipes
=> adaptions due to changes in pandapower

pandapipes/test/run_tests.py
due to changes in logger when running the tests there is a need to change this in pandapipes as well in order to ensure that all tests on master are still running
=> logger changes in pandapower

pandapipes/create.py, pandapipes/std_types/std_type_toolbox.py, pandapipes/test/api/test_components/test_pump.py, pandapipes/test/api/test_create.py
* regression_degree -> reg_polynomial_degree
* regression_parameters -> poly_coefficents
resolves issue #105
=> rename some parameters in create_pump

pandapipes/std_types/std_type.py
adding a new method to create a std_type: from_list --> given two arr…ays with pressure and volumne values
=> adding a new method to create a std_type

.travis.yml, pandapipes/io/file_io.py, pandapipes/io/io_utils.py
adaption of ppipe_hook: increasing recycability and enabling compatibility with pandapower
=> Adaption ppipe hook

pandapipes/properties/hydrogen/compressibility.txt, pandapipes/properties/hydrogen/der_compressibility.txt, pandapipes/properties/lgas/compressibility.txt, pandapipes/properties/lgas/der_compressibility.txt
* add compressibility and der_compressibility to hydrogen properties
This is based on the currently implemented approach (der_comp is independent of the temperature) to get it working somehow. Temperature dependent compressibility factors will probably also require changes in hgas properties.
=> add compressibility for H2 (simple)

pandapipes/plotting/generic_geodata.py, pandapipes/test/topology/test_graph_searches.py, pandapipes/test/topology/test_nxgraph.py, pandapipes/topology/__init__.py, pandapipes/topology/create_graph.py
- carry over new artificial coordinate functions from pandapower https://github.com/e2nIEE/pandapower/pull/901/commits/624fc91c79eadcf79cd58d48b6bc466fafc835bc
- add functionality to create_networkx graph for pandapipes networks
- tests for connected components searches in pandapipes networks
Works with current pandpower/develop version
ToDo: respect_valves functionality
=> Igraph and Networkx graphes

CHANGELOG.rst, pandapipes/test/api/old_versions/example_0.2.0.json, pandapipes/test/api/release_cycle/release_control_test_network.py
-bugfix in CHANGELOG.rst
-changes of line seperator
-new release control version
=> small fixes and updates

pandapipes/test/api/test_components/test_pump.py
* hydraulic calculation did not converge at mass flow = 1e6 kg/s and iter=3
* limit mass flow to 1000 kg/s
* increase iterations to 30
=> fix in test_pump_bypass_high_vdot

CHANGELOG.rst, doc/source/about.rst, doc/source/about/changelog.rst
* and little fix in date format
=> include change log in doc

.travis.yml, pandapipes/io/file_io.py, pandapipes/io/io_utils.py, pandapipes/properties/fluids.py, pandapipes/test/properties/test_fluid_specials.py
removing net to prevent circular references
(only merge after clean_control_2.0 has been merged in pandapower)
=> Clean control

doc/source/components/junction/junction_component.rst, doc/source/components/pipe/pipe_component.rst, doc/source/components/sink/sink_component.rst, doc/source/components/source/source_component.rst, doc/source/components/valve/valve_component.rst, pandapipes/create.py, pandapipes/test/api/test_create.py
Functions implemented for
- junctions
- sinks
- sources
- pipes
- pipes_from_parameters
- valves
Tests implemented for
- junctions
- sinks
- sources
- pipes_from_parameters
=> Bulk create functions

pandapipes/pipeflow.py, pandapipes/test/api/test_special_networks.py
Solving problem if there is only a one node net without branches. Corresponding tests added!
=> bugfix in pipeflow when there are only one node nets 

pandapipes/properties/fluids.py
there was a problem with Travis CI in the first PR
=> add methane in call_lib to gaseous fluids

pandapipes/pipeflow.py
set respective logger level to "debug"
@dlohmeier please check briefly (just some minor changes)
=> reduce pipeflow output printout (closes #163)

pandapipes/std_types/std_type.py
In pandagrids we need the original pressure and flowrate values, therefore, I need to keep them in the Pump class.
=> update Pump std type in order to still be able to access the original pressure and flowrate data if they exist

doc/source/multi_energy_nets/me_time_series.rst, doc/source/multi_energy_nets/multinet.rst
=> some linguistic perfectionism

pandapipes/__init__.py
to allow for command like pp.plotting.simple_plot(net)
=> add plotting to main init

pandapipes/test/topology/test_graph_searches.py, pandapipes/test/topology/test_nxgraph.py, pandapipes/topology/create_graph.py
Creation of networkx graph now based on component models. For all branch components, it is possible to add arguments stating that
- they are (not) included or which elements to include
- whether the active (in_service) status shall be respected (don't include oos elements)
- how to get the weighting for those branches
=> changes to topology structure

doc/source/components.rst, doc/source/conf.py, doc/source/networks.rst, doc/source/references.bib, pandapipes/networks/simple_gas_networks.py
* fix bibtex path
* add info on pandapipes net
=> Additions to documentation

pandapipes/plotting/generic_geodata.py
=> bugfix in genergic_geodata.py

setup.py
adaption of setup.py --> adding Jolando and version tag
=> Release 0.3.0

pandapipes/control/run_control.py, pandapipes/multinet/control/run_control_multinet.py, pandapipes/multinet/timeseries/run_time_series_multinet.py, pandapipes/test/pipeflow_internals/test_time_series.py
bugfix in control and timeseries due to changes in pandapower
=> Bugfix in control and time series

pandapipes/properties/hydrogen/compressibility.txt, pandapipes/properties/hydrogen/der_compressibility.txt
adjust compressibility and der_compr in properties/hydrogen/
=> change Z paramters for H2 to 273.15 K

doc/source/index.rst, doc/source/toolbox.rst, pandapipes/multinet/control/run_control_multinet.py, pandapipes/timeseries/run_time_series.py, pandapipes/toolbox.py
* and minor adjustments in some docstrings
=> add toolbox chapter to documentation

pandapipes/properties/fluids.py
... because it is a linear function of pressure, not temperature
=> change parameter name and docstring in get_compressibility

pandapipes/networks/__init__.py, pandapipes/networks/simple_heat_transfer_networks.py
Import of heat transfer networks added according to issue #265 
closes #265
=> Update networks init - import heat networks

pandapipes/create.py
=> little fix in docstrin (create_heat_exchanger)

pandapipes/component_models/abstract_models/branch_models.py, pandapipes/component_models/abstract_models/branch_w_internals_models.py
fixing bug if there are no pipes at all
=> bugfix if there are no pipes

pandapipes/component_models/ext_grid_component.py
currently out of service ext grids are considered still in service with a pressure of 0 bar. Is fixed !
=> bug in ext grids

pandapipes/multinet/control/controller/multinet_control.py, pandapipes/test/multinet/test_control_multinet.py
=> add 'scaling' to multi net controllers

pandapipes/test/api/test_components/test_valve.py
* now, the parameter k_mm is given in create_pipe instead of k (k has no meaning)
=> fix k in test_valve

pandapipes/component_models/abstract_models/branch_w_internals_models.py, pandapipes/component_models/auxiliaries/component_toolbox.py, pandapipes/component_models/pipe_component.py
=> hotfix for numpy type error when using unsigned integer with np.repeat

pandapipes/component_models/pump_component.py
added a logger error in case of using a fluid without molar mass, while trying to retrieve the compression power
=> compression power without molar mass

pandapipes/component_models/junction_component.py, pandapipes/converter/__init__.py, pandapipes/converter/stanet/__init__.py, pandapipes/converter/stanet/data_cleaning.py, pandapipes/converter/stanet/preparing_steps.py, pandapipes/converter/stanet/stanet2pandapipes.py, pandapipes/converter/stanet/table_creation.py, pandapipes/pf/derivative_calculation.py, pandapipes/pf/internals_toolbox.py, pandapipes/properties/fluids.py, pandapipes/timeseries/run_time_series.py
Still missing:
- FluidPropertySutherland get_at_integral_value
- valve_pipe component from STANET
- tests
- ...
=> Stanet conversion

pandapipes/component_models/junction_component.py, pandapipes/pf/derivative_calculation.py, pandapipes/pf/internals_toolbox.py, pandapipes/timeseries/run_time_series.py
- der_lambda could fail in some cases due to a bad correction term
- NetCalculationNotConverged error added to possible pandapipes errors in run_timeseries
- added some cases for numba calculations in _sum_by_group
=> some bug fixes

.github/workflows/run_tests_develop.yml, .github/workflows/run_tests_master.yml, .gitignore, CHANGELOG.rst, pandapipes/test/__init__.py, pandapipes/test/run_tests.py, setup.py
Extend the pytest tests to all jupyter notebooks in the tutorials folder.
=> add tutorial tests

setup.py
on pypi, the first e-mail address is linked in the "mail to" meta data
=> remove outdated contact information

pandapipes/component_models/abstract_models/branch_models.py, pandapipes/component_models/component_toolbox.py, pandapipes/component_models/junction_component.py, pandapipes/pf/build_system_matrix.py, pandapipes/pf/internals_toolbox.py, pandapipes/pf/pipeflow_setup.py, pandapipes/pipeflow.py, pandapipes/test/api/test_aux_function.py, pandapipes/test/pipeflow_internals/test_pipeflow_analytic_comparison.py, pandapipes/test/pipeflow_internals/test_transient.py, pandapipes/test/plotting/test_pipeflow_results.py
This is a merge from the develop branch of @dcronbach which already included first aspects of transient heat transfer simulation and the current develop branch which has been updated to include numba speedup and other features.
=> Transient heat transfer simulation

pandapipes/io/convert_format.py, pandapipes/io/io_utils.py
=> Format version

pandapipes/converter/stanet/preparing_steps.py
set the encoding typ variable to adjust in the read_options. If nothing is given encoding = "cp1252"
@dlohmeier please review this changes
=> variable encodings in read_option

pandapipes/create.py
* fix too long lines in the examples
=> beautify doc for circ_pumps

pandapipes/topology/create_graph.py
Hotfix for nx_graph creation of networks with flow controllers, as the keywords concerning them were not correctly considered within the function (include_flow_controls could not be set to False).
=> Flow control is considered in nx_graph creation

.github/workflows/run_tests_develop.yml, .github/workflows/run_tests_master.yml, CHANGELOG.rst, pandapipes/pipeflow.py
closes #500 
`np.bool` is deprecated and had to be replaced by bulit-in `bool`
numba does not support 3.11 yet
=> Add Python 3.11

CHANGELOG.rst, README.rst
it's broken and we are no longer using Travis CI
=> remove travis badge

.readthedocs.yml
Reverts e2nIEE/pandapipes#558
It is not working correctly on RTD
=> Revert "Update .readthedocs.yml"

src/pandapipes/component_models/abstract_models/circulation_pump.py
=> fixed error for setting output pressure in case of oos circulation pumps

src/pandapipes/converter/stanet/valve_pipe_component/valve_pipe_plotting.py, src/pandapipes/create.py, src/pandapipes/plotting/collections.py, src/pandapipes/plotting/plotting_toolbox.py
Hopefully all tests are working again -> only implemented the previous versions of used pandapower functions that were changed so that the tests did not work anymore.
=> Fix pandapower GEOJSON problems

.github/workflows/run_tests_develop.yml, .github/workflows/run_tests_master.yml
-added relying github tests
-removed codecov from relying tests
=> GitHub tests

.github/workflows/run_tests_develop.yml, .github/workflows/run_tests_master.yml
github workflow for develop tests: make tutorial tests use pandapower master instead of develop
=> tutorial tests with pandapower master

src/pandapipes/plotting/plotting_toolbox.py
in plotting toolbox: specify columns of geodata for which to calculate min / max in distance calculation
=> Hotfix plotting toolbox

CHANGELOG.rst, src/pandapipes/io/file_io.py, src/pandapipes/multinet/control/run_control_multinet.py, src/pandapipes/multinet/multinet.py, src/pandapipes/toolbox.py
Hi,
while doing some simulations I figured out, that some imports did not work correctly. 
This should import the correct paths / code.
BR
=> fixed some imports from pandapower.

.github/workflows/run_tests_develop.yml, .github/workflows/run_tests_master.yml
See https://github.com/e2nIEE/pandapower/pull/2450
=> fixed docs_check pipeline

src/pandapipes/__init__.py, src/pandapipes/create.py
fixed import if pandapipes is not installed and removed a not found dependency which broke tests
=> [FIX] fixed imports and dependencies to pandapower 3.0.0

src/pandapipes/plotting/generic_geodata.py, tutorials/height_difference_example.ipynb
extension of build igraph function
- speedup by using add_edges instead of iterating and avoidance of pandas .loc
- user input for weight column
- user input for additional component models
=> Feature/ buildup igraph

pyproject.toml, src/pandapipes/create.py
after merge of https://github.com/e2nIEE/pandapower/pull/2563/files, this needs to be merged as well
=> check name change
